version: '3'
services:
  payroll-database:
    platform: linux/x86_64
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD:-secret}"
      MYSQL_DATABASE: payroll
      MYSQL_USER: payroll
      MYSQL_PASSWORD: payroll
    ports:
      - '33106:3306'
    volumes:
      - ./docker/mysql:/var/lib/mysql
    restart: "unless-stopped"

  payroll-php:
    depends_on:
      - payroll-database
    build:
      context: .
    user: "${UID:-1000}:${GID:-1000}"
    volumes:
      - ./:/payroll
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: "unless-stopped"

  payroll-nginx:
    depends_on:
      - payroll-php
      - payroll-database
    image: nginx:stable-alpine
    ports:
      - '8081:80'
    volumes:
      - ./:/payroll
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    restart: "unless-stopped"
